# ----------------------------------------------------------------------------
#   Settings for "Fake Startup Guru".
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
#   Gatherer settings
# ----------------------------------------------------------------------------
gatherer:

    # Starting point, the JSON from the SWOOP data set
    swoop_json_uri:     "https://github.com/StartupWeekend/googleio_contest/raw/master/datasets/events.json"

    # Where to persist the data. Filepaths are relative to this config file's
    # location.
    sqlite_filepath:    "../data/database.sqlite"
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
#   Analyzer settings.
# ----------------------------------------------------------------------------
analyzer:

    # Number of K-folds to use for cross-validation.
    number_of_k_folds:  10

    # Where to persist the tagged and chunked data as a pickle. This takes
    # a long time to generate so will be useful to store off. Despite being
    # tagged and chunked it's of course segmented and tokenized so can e.g.
    # do word counts.
    tagged_chunked_filepath:    "../data/tagged_chunked.pickle"
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
